### ISSUE TITLE
Change of relation mapping from skos:exactMatch to others (broader,narrower..) ?

### ISSUE THREAD

**Issue by billmetangmo** [insight-centre/naisc#10]
Hello,

Thanks for sharing this with community.
I don't know where to ask my question so I ask it here.
When using naisc with meas , i can modify the entities mapping manually after a run however i can't modify the relation mapping which is always skos:exactMatch.

Is there a way to change this behaviour ?
I executed the mapping with configs/auto.json

Regards,

**Comment by jmccrae** [comment]
If you want to be able to predict different kinds of relations you will need to train the system on a dataset with that relation. The model then remembers and predicts that relation. You can even train a system that predicts multiple relations, however this is still a bit experimental and the performance is not so great.
