### ISSUE TITLE
server http://server1.nlp.insight-centre.org/naisc-models not available

### ISSUE THREAD

**Issue by vchapurlat** [insight-centre/naisc#23]
Dear John
We try to use Naisc, many thanks for this work.
However, we have met some issues with the server normally available on http://server1.nlp.insight-centre.org/naisc-models, in order to get the jaccard.libsvm.gz file then install jaccard.libsvm library. 
The server seems out of order or something equivalent. Could you help us please?
With best regards and thank you again.
Vincent
vincent.chapurlat@mines-ales.fr

**Comment by jmccrae** [comment]
Fixed now.
